# Generated by Django 2.2 on 2019-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190426_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('f', 'feminino'), ('m', 'masculino')], max_length=1, null=True),
        ),
    ]
